# Site
repository: incidentalfloma/cv
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Florence (Flo) Doo, MD MA
title: |
  Abdominal Radiologist &
  Climate Health/Artificial Intelligence Researcher
email: fdoo@som.umaryland.edu

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: flo_doo
github_username: incidentalfloma
linkedin_username: flodoo
orcid_username: 0000-0001-6519-5222


# About Section
# about_title: About Me
about_profile_image: images/FloDoo_photo.png
about_content: | 
  - Assistant Professor in the [Dept of Radiology and Nuclear Medicine](https://www.medschool.umaryland.edu/profiles/doo-florence-xini/)
  - Faculty at the [University of Maryland-Institute for Health Computing (UM-IHC)](https://www.ihc.umd.edu/)
  - Director of Innovation at the [University of Maryland Medical Intelligent Imaging (UM2ii) Center](https://www.medschool.umaryland.edu/um2ii/)

  As a physician innovator, my current research interests include translating technologies into clinical patient benefit, with a focus on sustainable AI and global health/climate change impacts.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Sustainability & Climate Health
        description: |
          Explore radiology’s (+radiology AI's) role in promoting sustainability within healthcare, to improve health outcomes.
          
          Funding: In part by <mark><a href="https://www.jhumacche.org/investigator-development-core" target="_blank">Johns Hopkins MACCHE</a></mark> and <mark><a href="https://www.aur.org/cerraf-fellows-and-research-projects" target="_blank">AAR CERRAF</a></mark> grants.

          Relevant publications:
          - [Optimal Large Language Model Characteristics to Balance Accuracy and Energy Use for Sustainable Medical Applications](https://pubs.rsna.org/doi/abs/10.1148/radiol.240320)
          - [Evaluation of Climate-Aware Metrics Tools for Radiology Informatics and Artificial Intelligence: Toward a Potential Radiology Ecolabel](https://www.jacr.org/article/S1546-1440(23)00960-2/abstract)
          - [Planetary Health and Radiology: Why We Should Care and What We Can Do](https://pubs.rsna.org/doi/epdf/10.1148/radiol.240219)
          - [Economic and Environmental Costs of Cloud Technologies for Medical Imaging and Radiology Artificial Intelligence](https://www.jacr.org/article/S1546-1440(23)00934-1/abstract)

      - layout: left
        title: Clinical/Translational Artificial Intelligence
        description: |
          Translate clinical AI tools & large language models (LLMs) for clinical use, focusing on patients & sociotechnical determinants of health.
          
          Funding: In part by <mark><a href="https://www.umms.org/ummc/innovation-challenge/awardees/2023-awardees" target="_blank">2024-2025 UMMC Innovation Challenge</a></mark>.

          Relevant publications:
          - [Exploring the Clinical Translation of Generative Models Like ChatGPT: Promise and Pitfalls in Radiology, From Patients to Population Health](https://www.jacr.org/article/S1546-1440(23)00516-1/abstract)
          - [Building Diversity, Equity, and Inclusion Within Radiology Artificial Intelligence: Representation Matters, From Data to the Workforce](https://www.jacr.org/article/S1546-1440(23)00506-9/abstract)
          - [Predicting Patient Demographics From Chest Radiographs With Deep Learning](https://pubmed.ncbi.nlm.nih.gov/35964688/)
          - [General-Purpose Large Language Models Versus a Domain-Specific Natural Language Processing Tool for Label Extraction From Chest Radiograph Reports](https://ajronline.org/doi/10.2214/AJR.23.30573)

# Footer
# footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

# https://github.com/sproogen/modern-resume-theme/blob/master/_config.yml
